#!/usr/bin/expect -f

set timeout -1
set send_human {.1 .3 1 .05 2}

spawn bash ./acunetix_23.9.231005181_x64.sh

expect ">>>"

send -h "\r\n"
send -h "\x03"

send -- "q"

expect "Accept the license terms?"
send -h "yes\r"

expect "Insert new hostname, or leave blank to use"
send -h "\r"

expect "Email:"
send -h "admin@admin.com\r"
expect "Password:"
send -h "Password123\r"
expect "Password again:"
send -h "Password123\r"

expect eof
